### ISSUE TITLE
когда я пытаюсь запустить скрипт появляется ошибка

### ISSUE THREAD

**Issue by Hello-world-pro** [synalice/vk-add-whole-playlist#3]
когда я пытаюсь запустить скрипт появляется ошибка
![wscript_QWtUXi3VaM](https://github.com/synalice/vk-add-whole-playlist/assets/159934284/75a935d8-9833-48cd-a4f4-53b00d8e80be)

**Comment by Hello-world-pro** [comment]
помогите, в чём может быть проблема?

**Comment by nikableh** [comment]
Получилось решить проблему?
